### ISSUE TITLE
HUD is hidden in mission mode

### ISSUE THREAD

**Issue by BlueStaggo** [DarioSamo/OriginsBlurFix#1]
I used HedgeModLoader to apply this mod. However, the HUD is not shown in mission mode. I played a bit outside mission mode and the HUD is still there. The only other mod I'm using is [Sonic 3 - Complete Music Restoration](https://gamebanana.com/sounds/61731). Here's an example of the missing HUD in Ring Vacuum 2:
![image](https://user-images.githubusercontent.com/71090710/175560709-43d3f792-2d55-406f-b8c7-4c824b421f8f.png)

**Comment by DarioSamo** [comment]
Ah, maybe this is what the mysterious second texture is for. I'll try to see what's up.

**Comment by DarioSamo** [comment]
Can you check the latest update?

**Comment by BlueStaggo** [comment]
Thanks! I can see the HUD now.

**Comment by Yeetj1243** [comment]
I can't find the file download for the HedgeModLoader. can you send the link?
